### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by gregbrochill** [princefishthrower/awesome-shell-prompt-colors#1]
This script is awesome!  I'm noticing that when I'm using the bash version and I use the up arrow to access a previous command, the prompt seems to overwritten.  Any ideas as to what's causing this? (Image attached)
![issue](https://github.com/princefishthrower/awesome-shell-prompt-colors/assets/65643039/71afcf1f-fc79-4377-8096-0a1afe3faaac)

**Comment by gregbrochill** [comment]
Found the bug, fixed it in the fork!  The escape sequences of the colors needed to be modified a variable needed to be added to a line.

**Comment by princefishthrower** [comment]
Will need to check this, on macos with `zsh` no such fix is needed
